data:
	mkdir -p data
	cd data;https://github.com/jennybc/gapminder/blob/main/inst/extdata/gapminder.tsv; curl -LO https://github.com/jennybc/gapminder/blob/main/inst/extdata/gapminder.tsv?raw=true
fig1:
	mkdir -p img
	python -B src/fig1.py
fig2:
	mkdir -p img
	python -B src/fig2.py
fig3:
	mkdir -p img
	python -B src/fig3.py
fig4:
	mkdir -p img
	python -B src/fig4.py
clean:
	rm -rf data
	rm -rf img
